# Generated by Django 5.0.4 on 2024-04-21 16:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_phoneuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
