# Generated by Django 5.0.4 on 2024-04-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phoneuser_referred_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReferral',
        ),
    ]
