# Generated by Django 5.0.4 on 2024-04-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_userreferral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneuser',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent', to=settings.AUTH_USER_MODEL),
        ),
    ]
